export interface IUser {
    nome: string,
    password: string,
    login: string,
    email: string,
    token: string,
    cpf: string,
    DDI: string,
    DDD: string,
    num_telefone: string,
    logradouro: string,
    num_endereco: string,
    bairro: string,
    cep: string,
    cidade: string,
    estado: string,
}